import { describe, expect, it } from 'vitest';
import type { Task } from '@prisma/client';
import {
  agentSystemPrompt,
  buildPrBody,
  changesUserContent,
  changesUserMessage,
  commitMessageFromResponse,
  fallbackBranchSlug,
  maxBranchSlugLength,
  proposalsSystemPrompt,
  slugify,
} from '../src/lib/agent-prompts.js';

// Locking tests for the pure prompt/slug builders extracted from agent-loop.ts.

const task = (over: Partial<Task>): Task =>
  ({ id: 'abcdef1234567890', title: 'Fix the bug', prompt: null, ...over }) as Task;

describe('slugify', () => {
  it('kebab-cases text', () => {
    expect(slugify('Hello World! Foo_bar', 40)).toBe('hello-world-foo-bar');
  });

  it('collapses and trims dashes', () => {
    expect(slugify('--a---b--', 40)).toBe('a-b');
  });

  it('caps length and strips a dangling dash left by the slice', () => {
    expect(slugify('abcde-ghij', 6)).toBe('abcde');
    expect(slugify('abcdefghij', 4)).toBe('abcd');
  });

  it('returns an empty string when nothing is slug-able', () => {
    expect(slugify('!!!', 40)).toBe('');
  });
});

describe('branch slug helpers', () => {
  it('maxBranchSlugLength leaves room for the prefix, floored at 8', () => {
    expect(maxBranchSlugLength('lemniscate/')).toBe(40 - 'lemniscate/'.length);
    expect(maxBranchSlugLength('a'.repeat(40))).toBe(8);
  });

  it('fallbackBranchSlug is task-<id prefix>', () => {
    expect(fallbackBranchSlug('abcdef1234567890', 30)).toBe('task-abcdef12');
  });
});

describe('commitMessageFromResponse', () => {
  const fallback = 'chore: apply lemniscate agent changes';

  it('takes the first non-empty line, stripped of surrounding quotes', () => {
    expect(commitMessageFromResponse('\n "feat: add x" \nmore', fallback)).toBe('feat: add x');
  });

  it('caps at 72 characters', () => {
    expect(commitMessageFromResponse('a'.repeat(100), fallback)).toBe('a'.repeat(72));
  });

  it('falls back when the response has no usable line', () => {
    expect(commitMessageFromResponse('\n  \n', fallback)).toBe(fallback);
    expect(commitMessageFromResponse('""', fallback)).toBe(fallback);
  });
});

describe('buildPrBody', () => {
  it('uses the trimmed prompt when present', () => {
    const body = buildPrBody(task({ prompt: '  do the thing  ' }), 'summary here');
    expect(body).toContain('do the thing');
    expect(body).toContain('summary here');
    expect(body).toContain('_Generated by the Lemniscate agent_');
  });

  it('falls back to the title when the prompt is missing or blank', () => {
    expect(buildPrBody(task({}), 's')).toContain('Fix the bug');
    expect(buildPrBody(task({ prompt: '   ' }), 's')).toContain('Fix the bug');
  });
});

describe('system prompts', () => {
  it('agentSystemPrompt demands strict JSON and appends owner instructions', () => {
    const prompt = agentSystemPrompt('always use tabs');
    expect(prompt).toContain('STRICT JSON');
    expect(prompt).toContain('Additional instructions from the repository owner:');
    expect(prompt).toContain('always use tabs');
  });

  it('agentSystemPrompt omits the owner block when no extra is set', () => {
    expect(agentSystemPrompt(null)).not.toContain('Additional instructions');
  });

  it('proposalsSystemPrompt asks for up to 5 tasks as a JSON array', () => {
    const prompt = proposalsSystemPrompt(null);
    expect(prompt).toContain('up to 5');
    expect(prompt).toContain('[{"title": string, "prompt": string}]');
  });
});

describe('changesUserContent', () => {
  it('embeds title, prompt, and repo context', () => {
    const content = changesUserContent(task({ prompt: 'details' }), 'CTX');
    expect(content).toBe('# Task\nFix the bug\n\ndetails\n\n# Repository context\nCTX');
  });

  it('omits the prompt line when absent', () => {
    expect(changesUserContent(task({}), 'CTX')).toBe('# Task\nFix the bug\n\n\n# Repository context\nCTX');
  });
});

describe('changesUserMessage', () => {
  const png = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUg==';

  it('returns plain string content when the task has no attachments', () => {
    const message = changesUserMessage(task({ prompt: 'details' }), 'CTX');
    expect(message.role).toBe('user');
    expect(message.content).toBe(changesUserContent(task({ prompt: 'details' }), 'CTX'));
  });

  it('builds multimodal content parts when attachments are stored', () => {
    const t = task({
      prompt: 'details',
      attachments: [{ name: 'shot.png', dataUrl: png }],
    });
    const message = changesUserMessage(t, 'CTX');
    expect(message.content).toEqual([
      { type: 'text', text: changesUserContent(t, 'CTX') },
      { type: 'image_url', image_url: { url: png } },
    ]);
  });

  it('ignores malformed stored attachments', () => {
    const t = task({ attachments: [{ name: 'broken' }] });
    const message = changesUserMessage(t, 'CTX');
    expect(typeof message.content).toBe('string');
  });
});
