import type { Task } from '@prisma/client';
import { config } from '../config.js';
import { llmCall, TokenBudgetExceededError, type LlmRuntime } from './agent-runtime.js';

// Branch-name, commit-message, and PR-body helpers for the agent loop.
// Extracted from agent-prompts.ts to keep both modules under the 300-line
// guard (AGENTS.md §2); the pure builders are unit-tested in
// tests/agent-prompts.test.ts.

export function slugify(text: string, maxLength: number): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/-{2,}/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, maxLength)
    .replace(/-+$/g, '');
}

// Branch name: LLM-proposed slug, sanitized, prefix + slug ≤ 40 chars.
export function maxBranchSlugLength(prefix: string): number {
  return Math.max(8, 40 - prefix.length);
}

export function fallbackBranchSlug(taskId: string, maxSlugLength: number): string {
  return slugify(`task-${taskId.slice(0, 8)}`, maxSlugLength);
}

function branchSlugUserPrompt(maxSlugLength: number, task: Task): string {
  return [
    `Propose a short kebab-case git branch slug (max ${maxSlugLength} characters) for this task.`,
    'Reply with ONLY the slug, nothing else.',
    '',
    `Title: ${task.title}`,
    task.prompt ?? '',
  ].join('\n');
}

export async function generateBranchName(rt: LlmRuntime, task: Task): Promise<string> {
  const prefix = config.AGENT_BRANCH_PREFIX;
  const maxSlugLength = maxBranchSlugLength(prefix);
  const fallback = fallbackBranchSlug(task.id, maxSlugLength);
  try {
    const content = await llmCall(rt, [
      { role: 'user', content: branchSlugUserPrompt(maxSlugLength, task) },
    ]);
    return `${prefix}${slugify(content, maxSlugLength) || fallback}`;
  } catch (err) {
    if (err instanceof TokenBudgetExceededError) throw err;
    return `${prefix}${fallback}`;
  }
}

const COMMIT_MESSAGE_FALLBACK = 'chore: apply lemniscate agent changes';

function commitMessageUserPrompt(task: Task, summary: string): string {
  return [
    'Write a concise conventional-commit message (single line, max 72 characters) for these changes.',
    'Reply with ONLY the commit message, nothing else.',
    '',
    `Task: ${task.title}`,
    `Summary: ${summary}`,
  ].join('\n');
}

export function commitMessageFromResponse(content: string, fallback: string): string {
  const firstLine =
    content
      .split('\n')
      .map((line) => line.trim())
      .find((line) => line.length > 0) ?? '';
  const cleaned = firstLine.replace(/^["'`]+|["'`]+$/g, '').slice(0, 72).trim();
  return cleaned || fallback;
}

export async function generateCommitMessage(
  rt: LlmRuntime,
  task: Task,
  summary: string,
): Promise<string> {
  try {
    const content = await llmCall(rt, [
      { role: 'user', content: commitMessageUserPrompt(task, summary) },
    ]);
    return commitMessageFromResponse(content, COMMIT_MESSAGE_FALLBACK);
  } catch (err) {
    if (err instanceof TokenBudgetExceededError) throw err;
    return COMMIT_MESSAGE_FALLBACK;
  }
}

export function buildPrBody(task: Task, summary: string): string {
  return [
    '## Task',
    '',
    task.prompt?.trim() || task.title,
    '',
    '## Summary of changes',
    '',
    summary,
    '',
    '---',
    '_Generated by the Lemniscate agent_',
  ].join('\n');
}
